#!/usr/local/bin/bash
#==============================================================================
# ip_snmp_process_count-local_manifest.cgi
#
# Provide additional troubleshooting data in emails and tickets
# generated by this service check when critical (on any host).
#
# RT:129010
#==============================================================================
PATH=/bin:/usr/bin:/usr/local/bin

CMD="/usr/bin/grep local_manifest.cgi /data/var/log/httpd/updates.ironport.com/access.log | awk -F\"|\" '{if (\$2 ~ /.*[0-9].*/) print \$2}' | sed 's/,.*//g;s/\ //g' | sort -n | uniq -c | sort -n | tail -40"

echo "IPs that may be misusing local manifests:"
RESULT=`/usr/bin/ssh -o StrictHostKeyChecking=no -i /usr/local/var/nagios/.ssh/id_rsa nagios@${NAGIOS_HOSTADDRESS} "${CMD}" 2>&1`
if [ "${RESULT}" = "" ]; then
    echo "    No IPs were found"
else
   echo "${RESULT}"
fi
