#!/usr/local/bin/bash
#==============================================================================
# stale_publishing_locks
# -- NOTIFICATION HANDLER --
#==============================================================================
DB_HOST=${NAGIOS_HOSTADDRESS}
DB_USER="nagios"
DB_PASS="thaxu1T"
DB_NAME="updater"
SQL="select id,component_name,sync_lock,from_unixtime(lock_time) as lock_time from updates where (lock_time > 0) and (lock_time < (unix_timestamp() - 1800)) order by lock_time asc"
echo
echo
echo "STALE LOCKS FOUND IN MYSQL QUERY (there should be none)"
echo
/usr/local/bin/mysql --host="${NAGIOS_HOSTADDRESS}" --user="${DB_USER}" --password="${DB_PASS}" --execute="${SQL}" ${DB_NAME}
echo
echo
exit 0
