#!/usr/local/bin/bash
#==============================================================================
# ironcat_process
# Try to put ironcat back to work.
#==============================================================================
# Restart ironcat
/usr/bin/ssh -o StrictHostKeyChecking=no -i ~nagios/.ssh/id_rsa nagios@${NAGIOS_HOSTADDRESS} "sudo /usr/local/etc/rc.d/ironcat.sh restart"

# Wait a few seconds to let it spin up
/bin/sleep 20

# Send a confirmation message to ironcat
/usr/local/ironport/nagios/bin/ironcat.sh "nagios restarted me on ${NAGIOS_HOSTADDRESS}"

exit 0
