#!/usr/local/bin/bash

# $1 = script
# ++ = args

# Ensure that user is listed in at.allow and not in at.deny.
# best also if the atrun crontab is set to a 1 minute interval.

PATH=/bin:/usr/bin:/usr/local/bin
# Make sure at doesn't inherit anything invalid
SHELL=/usr/local/bin/bash
HOME=/tmp
PWD=/tmp
cd /tmp

iam=`whoami`
script=$1
if [ "$2" != "" ]
then
    args=`echo $@ | cut -f2-99 -d\ `
else
    args=''
fi

if [[ "${script}" == "" ]] || [[ ! -x "${script}" ]]
then
    echo "usage:"
    echo "$0 <script> [<arguments>]"
    echo "Please use full pathnames for <script>"
    exit 3
fi

echo "$1 $ARGS" >> /tmp/precache-${iam}

if [ ! -d /tmp/cache-${iam}/ ]
then
    mkdir /tmp/cache-${iam}
fi

cf="/tmp/cache-${iam}/`echo ${script} ${args} | sed -e 's/\//_/g' | tr \  _`"

if [ ! -f ${cf} ]
then
    echo "No cache detected for ${cf}"
else
    cat < ${cf}

fi

atout=`echo "${script} ${args} > ${cf} 2>&1 ; echo "'$?' "> ${cf}.out" | at now 2>&1`
if [ $? != 0 ]
then
    echo Error running at.  Please ensure that ${iam} is in at.allow,
    echo and not in at.deny.  This would be a good time to ensure that
    echo the atrun frequency is set to once per minute as well.
fi

#job=`echo ${atout} | cut -f2 -d\ `
#job=`at -c ${job}`
#if [ "$job" != "" ]
#then
#printf "%b" "${atout}\n\n${job}" | wall
#printf "%b" "${atout}\n\n${job}" > /tmp/at.out
#fi
if [ -f ${cf}.out ]
then
    exit `cat ${cf}.out`
else
    echo No exit code found.
    echo 
    printf "%b" "${atout}"
    exit 3
fi


