#!/usr/local/bin/bash
#=======================================================================
# vmdc-vmfs
#
# Send email notification when vcenter data store consumption exceeds
# warning threshold.
# 
# 2013-01-17, jramache, re-worked an existing vmdc-vmfs handler
#=======================================================================
PATH=/bin:/usr/bin:/usr/local/bin:/usr/local/ironport/nagios/bin

if [[ "${NAGIOS_SERVICEOUTPUT}" != *not\ authenticated* && "${NAGIOS_SERVICEOUTPUT}" != *ended\ unexpectedly* ]]
then
    LONG_OUTPUT="`nagiosstatc -q \"status service ${NAGIOS_HOSTNAME} ${NAGIOS_SERVICEDESC} long_plugin_output\" | cut -f6 -d\\"`"
    LONG_OUTPUT="`printf \"%b\" \"${LONG_OUTPUT}\"`"

    MESSAGE="Hello, Capacity Planners -

Usage on one or more data stores exceeds WARNING threshold!
Review output below and take appropriate action.

VCENTER: ${NAGIOS_HOSTNAME}
SERVICE: ${NAGIOS_SERVICEDESC}

${NAGIOS_SERVICEOUTPUT}
${LONG_OUTPUT}

Will escalate if problem continues.
"
    printf "%b" "${MESSAGE}" | mail -s "NAGIOS WARNING: Data store usage on ${NAGIOS_HOSTNAME}" stbu-capacity-management@cisco.com, stbu-platops@cisco.com
fi
exit 0