# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

# general packages:
package ifneeded opscfg 1.1 [list source [file join $dir cfg.tcl]]
package ifneeded opsprns 1.0 [list source [file join $dir prns.tcl]]
package ifneeded opslogger 0.2 [list source [file join $dir logger.tcl]]
package ifneeded opsdb 0.2 [list source [file join $dir db.tcl]]
package ifneeded opsssh 0.2 [list source [file join $dir ssh.tcl]]
package ifneeded opsparsers 0.2 [list source [file join $dir parsers.tcl]]
package ifneeded opsredis 0.1 [list source [file join $dir redis.tcl]]
# monitoring specific packages:
package ifneeded mondiablo 0.2 [list source [file join $dir mondiablo.tcl]]
package ifneeded monoutput 0.3 [list source [file join $dir monoutput.tcl]]
package ifneeded monwmi 0.1 [list source [file join $dir monwmi.tcl]]

# Local Variables:
# mode: tcl
# coding: utf-8-unix
# comment-column: 0
# comment-start: "# "
# comment-end: ""
# End:
